FROM bitnami/spark:3.3.2-debian-11-r22

USER root
RUN apt-get update && apt-get install -y \
    curl gcc python3
RUN pip install \
    requests==2.31.0 \
    kafka-python==2.0.2 \
    cassandra-driver==3.25.0

RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.2/hadoop-client-api-3.3.2.jar -o /opt/bitnami/spark/jars/hadoop-client-api-3.3.2.jar 
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.2/hadoop-client-runtime-3.3.2.jar -o /opt/bitnami/spark/jars/hadoop-client-runtime-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/2.8.1/kafka-clients-2.8.1.jar -o /opt/bitnami/spark/jars/kafka-clients-2.8.1.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.2/spark-sql-kafka-0-10_2.12-3.3.2.jar -o /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.2/spark-token-provider-kafka-0-10_2.12-3.3.2.jar -o /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.3.2.jar
RUN curl https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar -o /opt/bitnami/spark/jars/lz4-java-1.8.0.jar
RUN curl https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.1/postgresql-42.3.1.jar -o /opt/bitnami/spark/jars/postgresql-42.3.1.jar
RUN curl https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar -o /opt/bitnami/spark/jars/unused-1.0.0.jar
RUN curl https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_2.12/3.3.0/spark-cassandra-connector_2.12-3.3.0.jar -o /opt/bitnami/spark/jars/spark-cassandra-connector_2.12-3.3.0.jar
RUN curl https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar -o /opt/bitnami/spark/jars/commons-logging-1.1.3.jar
RUN curl https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.4/snappy-java-1.1.8.4.jar -o /opt/bitnami/spark/jars/snappy-java-1.1.8.4.jar
RUN curl https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar -o /opt/bitnami/spark/jars/slf4j-api-1.7.32.jar
RUN curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar -o /opt/bitnami/spark/jars/commons-pool2-2.11.1.jar